# ==========================================
#   CONFIGURACIÓN VISUAL Y FUENTES
# ==========================================
font_family      FiraCode Nerd Font
font_size        11.0
cursor_shape     beam
disable_ligatures never

# ==========================================
#   VENTANA Y CRISTAL (TRANSPARENCIA)
# ==========================================
background_opacity 0.85
window_padding_width 10
hide_window_decorations yes

# ==========================================
#   COMPORTAMIENTO
# ==========================================
enable_audio_bell no
confirm_os_window_close 0

# ==========================================
#   COLORES ANSI (Sintaxis)
# ==========================================
# Mantenemos esto estático para no romper editores de texto ni comandos
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# ==========================================
#   TEMA DINÁMICO (MATUGEN)
# ==========================================
include /home/hyperZen/.config/matugen/output/kitty-colors.conf
