[config]
default_source_color = 0

[templates.waybar_swaync]
input_path = '/home/hyperZen/.config/matugen/templates/colors.css'
output_path = '/home/hyperZen/.config/matugen/output/colors.css'

[templates.rofi]
input_path = '/home/hyperZen/.config/matugen/templates/colors.rasi'
output_path = '/home/hyperZen/.config/matugen/output/colors.rasi'

[templates.kitty]
input_path = '/home/hyperZen/.config/matugen/templates/kitty-colors.conf'
output_path = '/home/hyperZen/.config/matugen/output/kitty-colors.conf'
