background {{colors.background.default.hex}}
foreground {{colors.on_background.default.hex}}
cursor {{colors.primary.default.hex}}
selection_background {{colors.surface_variant.default.hex}}
selection_foreground {{colors.on_surface_variant.default.hex}}
url_color {{colors.primary.default.hex}}
